### ISSUE TITLE
Question: CPIC levels for gene-drug pairs?

### ISSUE THREAD

**Issue by greg-sharpe** [cpicpgx/cpic-data#17]
Is there a way to determine the level of evidence for a given recommendation level or guideline? I was unable to find the supplementary material describing the "classification" attribute of a recommendation.

[The genes-drugs page of the CPIC website](https://cpicpgx.org/genes-drugs/) includes CPIC levels and PHARMGKB levels of evidence, which would be helpful to access via the API.

**Comment by whaleyr** [comment]
Your question is a bit vague so I will give a few different answers.

Each guideline (i.e. `guideline` data model) can have multiple recommendations (i.e. `recommendation` data model). Each one of those recommendations has an individual "classification of recommendation" (i.e. the `classification` property) which is reflected in the supplement.

For example: https://api.cpicpgx.org/v1/recommendation?id=eq.2085265 has a `classification` of "Strong".

The CPIC and PharmGKB levels represent completely different concepts. These are applied on the drug-gene pair level and can be seen in the [pair data model](https://api.cpicpgx.org/#/pair) (the previously mentioned classification is on the drug-phenotype level). You can read more about CPIC levels on [the prioritization page](https://cpicpgx.org/prioritization/) and about the [PharmGKB Level of Evidence on PharmGKB.org](https://www.pharmgkb.org/page/clinAnnLevels).

Does that answer your question?

**Comment by greg-sharpe** [comment]
Yes, thank you.
