### ISSUE TITLE
Dump sql file import

### ISSUE THREAD

**Issue by mdAdnn** [cpicpgx/cpic-data#19]
Hi,

I am using pgadmin4 to view my data. But I'm getting an error that it is a dump file.

How to run it in pgadmin4?
https://github.com/cpicpgx/cpic-data/releases/download/v1.21.3/cpic_db_dump-v1.21.3.sql.gz

**Comment by whaleyr** [comment]
I haven't used pgadmin4 so I can't give a specific answer but have you tried looking at this? https://stackoverflow.com/a/62175501

It would be best if you could run the `psql` command directly on the command line then you can run the file directly there: https://stackoverflow.com/a/6842496

**Comment by mdAdnn** [comment]
when using direct psql command its importing the data but unable to open

**Comment by whaleyr** [comment]
That's a very general description of a problem with postgresql, not necessarily about this dataset in particular. I highly recommend reading the official postgresql documentation, it's well-written and broad: https://www.postgresql.org/docs/15/app-psql.html

If you come up with a problem specific to this dataset feel free to reopen.
