### ISSUE TITLE
Comma encoding in gene_result_diplotype

### ISSUE THREAD

**Issue by greg-sharpe** [cpicpgx/cpic-data#20]
It looks like some diplotypes contain the 0x82 character for a comma, instead of the 0x2C character.
Edit: something with the way I was using notepad++ or googling must have been wrong. It's the Unicode 0x201A character in diplotypes with "Taipei" or "Panama".

If you download all of gene_result_diplotype from https://api.cpicpgx.org/v1/gene_result_diplotype? and view the JSON as ANSI encoded text, some diplotypes will contain â€š instead of a comma, such as:
 {"id":2699210,"functionphenotypeid":2699182,"diplotype":"Mediterranean, Dallas, Panamaâ€š Sassari, Cagliari, Birmingham","diplotypekey":{"G6PD": {"Mediterranean, Dallas, Panamaâ€š Sassari, Cagliari, Birmingham": 1}},"frequency":null}

[gene_result_diplotype.zip](https://github.com/cpicpgx/cpic-data/files/10272892/gene_result_diplotype.zip)

**Comment by whaleyr** [comment]
Thanks for catching that. We will work on standardizing some characters in the text fields.

Out of curiosity, what's the context that you're viewing this in? OS? Application? That's a valid UTF-8 character and `Content-Type` header of the response indicates it is `application/json; charset=utf-8`. Is your application assuming the charset and, thus, displaying it incorrectly?

**Comment by greg-sharpe** [comment]
I have a python script that uses requests.get on a few of the tables and manipulates the data I need, then writes it to a file that I import into a database that uses windows 1252 encoding. Regardless of my file's encoding, once it's imported into the database, the difference is apparent.

I can check for this specific issue in the script when manipulating the json data, but I thought you'd want to know about the inconsistency.

**Comment by greg-sharpe** [comment]
Also, there are a couple of unicode 0x2019 apostrophes and 0x2013 en-dashes

**Comment by whaleyr** [comment]
The text updates should be in the DB by this point. I'm closing, if it's still an issue please re-open.
