### ISSUE TITLE
Multiple recommendations for the same med

### ISSUE THREAD

**Issue by Darsh193** [cpicpgx/cpic-data#25]
Hello, I've observed that I receive multiple recommendations for the same medication, especially for medications that involve more than one gene. For instance, when I run the code for amitriptyline and other tertiary amines, I seem to be getting multiple recommendations. Is there something I might be overlooking? Thanks!

**Comment by whaleyr** [comment]
Can you give specifics? What genotype are you using to query? When you say you run the code which code are you running? If you're getting multiple recommendations can you post which recommendations you're getting and what criteria you're using to get them?

**Comment by Darsh193** [comment]
Thank you for your response! Sure, here is the query "https://api.cpicpgx.org/v1/recommendation?drugid=eq.RxNorm:704&lookupkey=cs.{%22CYP2D6%22:%221.0%22}&activityscore=cs.{%22CYP2D6%22:%221.0%22}" and here are the recommendations am getting for amitriptyline, clomipramine, doxepin, imipramine, andtrimipramine:

Population: general
Classification: Optional
Recommendation: Consider a 25% reduction of recommended starting dose. Utilizing therapeutic drug monitoring to guide dose adjustments is strongly recommended.


Population: general
Classification: Moderate
Recommendation: Consider a 25% reduction of recommended starting dose. Utilize therapeutic drug monitoring to guide dose adjustments.

Population: general
Classification: Optional
Recommendation: Avoid amitriptyline use; If amitriptyline is warranted, utilize therapeutic drug monitoring to guide dose adjustment. Utilizing therapeutic drug monitoring to guide dose adjustments is strongly recommended.


Population: general
Classification: Optional
Recommendation: Consider alternative drug not metabolized by CYP2C19; If amitriptyline is warranted, utilize therapeutic drug monitoring to guide dose adjustment. Utilizing therapeutic drug monitoring to guide dose adjustments is strongly recommended.

Population: general
Classification: Optional
Recommendation: Consider alternative drug not metabolized by CYP2C19; If amitriptyline is warranted, utilize therapeutic drug monitoring to guide dose adjustment. Utilizing therapeutic drug monitoring to guide dose adjustments is strongly recommended.


Population: general
Classification: Moderate
Recommendation: Consider a 25% reduction of recommended starting dose. Utilize therapeutic drug monitoring to guide dose adjustments. Titrate dose to observed clinical response with symptom improvement and minimal (if any) side effects.

So, Should I modify the query to combine both CYP2D6 and CYP2C19 gene statuses in order to return recommendations that consider both genes simultaneously?

**Comment by whaleyr** [comment]
A couple of things.

First, if you're doing a recommendation lookup you only need to use the `lookupkey` property. You can leave out the `activityscore` parameter. The `lookupkey` property is there to handle situations like this where two genes are used for lookup and they use different functional translations.

Second, you're using the `cs.` prefix for the `lookupkey` property which is a "contains" query. That will match any recommendation that includes CYP2D6 activity score 1.0. If you check the lookupkey property on each of those recommendaitons you'll see they all have different CYP2C19 values. Those are all the possible phenotypes for CYP2C19. Each one gets its own recommendation. If you don't have a CYP2C19 result but you still want to get a recommendation then you should use the `No Result` phenotype. The request would be:
```
https://api.cpicpgx.org/v1/recommendation?drugid=eq.RxNorm:704&lookupkey=cs.{"CYP2D6":"1.0", "CYP2C19": "No Result"}
```

**Comment by Darsh193** [comment]
I see, thank you so much for your comprehensive answer!
