### ISSUE TITLE
Warfarin doubt

### ISSUE THREAD

**Issue by aviguille** [cpicpgx/cpic-data#30]
Hi,

I know the guideline for warfarin has not been implemented in the database but I have problems interpreting the text. 

<img width="653" alt="image" src="https://github.com/cpicpgx/cpic-data/assets/11446753/75725100-6c8d-46ce-9aa3-f27a0351ceea">

In page 402 we can find this text: "In individuals with genotypes associated with CYP2C9 poor metabolism (e.g., CYP2C9 *2/*3, *3/*3) or both increased sensitivity (VKORC1-1639 A/A) and CYP2C9 poor metabolism, an alternative oral anticoagulant might be considered"

This can be represented as 
IF CYP2C9(PM) OR [VKORC1 (A/G OR A/A) AND CYP2C9(PM) ] --> consider alternative

But this is the same as (boolean logic): A + A*B, and will be True whenever A is True. That is, VKORC1 plays no role. Is this right?

Thanks

**Comment by whaleyr** [comment]
Follow the logic in the warfarin dosing recommendation diagram that is Figure 2 in the published guideline:
![](https://files.cpicpgx.org/images/warfarin/warfarin_recommendation_diagram.png)

If you have further questions about the algorithm I suggest emailing contact@cpicpgx.org
