### ISSUE TITLE
[Question] examples and public datasets to help with sequence_location to allele mapping

### ISSUE THREAD

**Issue by davidyuyuan** [cpicpgx/cpic-data#31]
Thank you for providing an example to find sequence_locations such as dbSNP IDs for a given gene and allele at https://github.com/cpicpgx/cpic-data/wiki#allele (e.g. CYP2D6*3).

In practice, users would want to find the allele *3 and related PGx recommendations with given a gene and sequence_locations (e.g. CYP2D6, rs1135824 and rs35742686). Would you please suggest a way for such reverse lookup? What if the sequence_locations have to be phased? Do you have a public dataset (BAM/CRAM or VCF, and sequence_location-allele mapping) to verify the correctness of the mapping from sequence_location to allele or from allele to sequence_location?

**Comment by whaleyr** [comment]
I think what you're looking for is [PharmCAT](https://pharmcat.org).

With PharmCAT you can supply genotype data and get specific CPIC recommendations. It's a bit more complicated than that but it should be all documented there.

**Comment by davidyuyuan** [comment]
I should have asked my question in a better way. I was hoping to get an example similar to what you have in https://github.com/cpicpgx/cpic-data/wiki#allele but the input is gene and dbSNP ID (e.g. CYP2D6, rs1135824 and rs35742686) and the output is genotype / star allele (e.g. *3) via the REST API. Do you know a way / ways to do this?

**Comment by whaleyr** [comment]
You're talking about allele matching, which is not supported by the CPIC API. It's a not as straight-forward as it may seem (see the [PharmCAT docs](https://pharmcat.org/methods/NamedAlleleMatcher-101/)) so single database select queries cannot properly do it. However, allele matching IS done by PharmCAT and I highly recommend you use that tool.

**Comment by davidyuyuan** [comment]
Thank you for the suggestion.
