### ISSUE TITLE
Allele location value of *2 in CYP2C19

### ISSUE THREAD

**Issue by davidyuyuan** [cpicpgx/cpic-data#37]
The database has included 4 variants in *2 in CYP2C19: rs12769205, **_rs58973490_**, rs4244285 and rs3758581. Please see response from the REST endpoint: https://api.cpicpgx.org/v1/allele_definition?genesymbol=eq.CYP2C19&select=genesymbol,name,allele_location_value(sequence_location(name,%20dbsnpid))&order=name.

However, PharmVar has only included 3 variants: rs12769205, rs4244285 and rs3758581. Here is a link for your convenience: https://www.pharmvar.org/gene/CYP2C19. The variant **_rs58973490_** is only part of 1 minor variant *2.010 in PharmVar and marked as limited evidance.

I am aware that the CYP2C19 allele definition table at CPIC includes rs58973490 in *2, where the mutation is G>R https://cpicpgx.org/guidelines/guideline-for-voriconazole-and-cyp2c19/. As R is G or A in the IUPAC table. Does that mean CPIC has not reached consensus on rs58973490, either?

Is there a reason to include rs58973490 as a core variant in *2 and defined as G>A mutation in the database?

**Comment by whaleyr** [comment]
I'm contacting our curators about this specific example, but if you want some good documentation about why we use ambiguity codes (wobbles) in some allele definitions please see: https://www.pharmgkb.org/page/coreAllelesAndWobbles

**Comment by davidyuyuan** [comment]
Thank you for sending the documentation on the use of ambiguity codes at CPIC. I am reading it with interest. Also, I am looking forward to hearing from your curators.

**Comment by whaleyr** [comment]
Spoke with curators. \*2 has a suballele that contains rs58973490 but the \*11 core allele also includes rs58973490 so the wobble was added to allow for the fact you could still be a \*2 even though you have rs58973490.

**Comment by davidyuyuan** [comment]
Hi Ryan,
Thank you for the prompt response. I'd like to bring to your attention that rs58973490 is named as "12802G>A" in *11, *2 and *38 in the database. The allele definition table in the guidelines is G>R for *2, G>A for *11 and G>G for *38. There seems inconsistency here. 

For your convenience, I am copying and pasting the Json response for *2 here:

{"genesymbol":"CYP2C19","name":"*2","allele_location_value":[{"sequence_location": {"name": "12662A>G", "dbsnpid": "rs12769205"}}, {"sequence_location": {"name": "12802G>A", "dbsnpid": "rs58973490"}}, {"sequence_location": {"name": "19154G>A", "dbsnpid": "rs4244285"}}, {"sequence_location": {"name": "80161A>G", "dbsnpid": "rs3758581"}}]}

**Comment by whaleyr** [comment]
Hi David, I see the problem now. The `sequence_location` model is a general description that corresponds to the column headers in the allele definition (`CYP2C19_allele_definition_table.xlsx`) sheet and is shared as a common object between all named alleles that have an entry in that column. It is NOT meant to be an HGVS representation of the specific variation for that specific named allele. That type of information is in the `allele_location_value` model. You'll see a property in there called `variantallele` which denotes the specific variant applicable to the parent `allele_definition`. The API request you posted earlier is leaving out the specific allele for the \*2 definition. So if you want to see the specific allele definition for \*2, a better API request would be:

```
https://api.cpicpgx.org/v1/allele_definition?genesymbol=eq.CYP2C19&name=eq.*2&select=*, allele_location_value(*, sequence_location(*))&order=name
```

**Comment by davidyuyuan** [comment]
Hi Ryan,
Thank you very much for pointing this out. I think that I need to make some code changes on my side to use the better API. Please close this issue.
Best regards,
David

**Comment by whaleyr** [comment]
If you're doing this level of detailed work with the CPIC data I think you will find it highly useful to run a local instance of the CPIC DB and then you can run all sorts of ad hoc queries and data model analysis. A full DB export is always available with each release: https://github.com/cpicpgx/cpic-data/releases
