### ISSUE TITLE
v1.40.0 is missing full DB export

### ISSUE THREAD

**Issue by joh06288** [cpicpgx/cpic-data#39]
In prior releases, a full DB export was made available as part of the release files.  

For v1.40.0, there is no link.  We expected it to be located at: https://files.cpicpgx.org/data/database/cpic_db_dump-v1.40.0.sql.gz

Can you update the release to include the full DB export?

**Comment by whaleyr** [comment]
There was a problem with the last data load that caused the export to fail. I've fixed it and the DB export has been posted to the release.
