### ISSUE TITLE
DPYD gene mapped to wrong HGNC id in gene table

### ISSUE THREAD

**Issue by bajrachar** [cpicpgx/cpic-data#42]
Hello @whaleyr,
Was trying to pick up the HGNC mappings for the CPIC genes and noticed that DPYD gene is mapped to HGNC:1806 [ which shows up as CDX2 gene  i.e https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:1806]. Should this be HGNC:3012 instead?

Many thanks

**Comment by whaleyr** [comment]
Thanks for letting me know, will get it updated.

**Comment by whaleyr** [comment]
This has been updated in the [API](https://api.cpicpgx.org/v1/gene?symbol=eq.DPYD) and in the [gene information files on PharmGKB](https://preview.pharmgkb.org/page/dpydRefMaterials).

The fix will be part of the next release.
