### ISSUE TITLE
Flesh out more data in publications table

### ISSUE THREAD

**Issue by whaleyr** [cpicpgx/cpic-data#7]
_Problem_: Currently, many rows in the `publication` table have no title or other data besides a single author, a year, and a PMID. Can we get more data filled in?

_Detail_: The rows with missing data come from source data files (mostly the frequency sheets) that list only author name, year, and PMID. We should add some code that can hit the PubMed API to gather more citation data and copy it into our table.

**Comment by mumtahena** [comment]
Problem: **"genes"** for the guideline queries are resulting as 'null' for all but the PPI and NSAID guidelines.
`curl --location --request GET 'https://api.cpicpgx.org/v1/guideline?select=*,publication(title,pmid,year)&order=genes'`

output>
[{"id":110076,"version":1,"name":"CYP2C19 and Proton Pump Inhibitors","url":"https://cpicpgx.org/guidelines/cpic-guideline-for-proton-pump-inhibitors-and-cyp2c19/","pharmgkbid":["PA166219103","PA166219301"],**"genes":["CYP2C19"],**"publication":[]}, 
 {"id":110058,"version":2,"name":"CYP2C9 and NSAIDs","url":"https://cpicpgx.org/guidelines/cpic-guideline-for-nsaids-based-on-cyp2c9-genotype/","pharmgkbid":["PA166191841"],**"genes":["CYP2C9"]**,"publication":[]}, 
 {"id":100416,"version":4,"name":"CYP2D6 and Codeine","url":"https://cpicpgx.org/guidelines/guideline-for-codeine-and-cyp2d6/","pharmgkbid":["PA166104996"],**"genes":null,**"publication":[{"title":"Clinical Pharmacogenetics Implementation Consortium (CPIC) Guidelines for Codeine Therapy in the Context of Cytochrome P450 2D6 (CYP2D6) Genotype","pmid":"22205192","year":2011}, 
 {"title":"Clinical Pharmacogenetics Implementation Consortium (CPIC) guidelines for cytochrome P450 2D6 (CYP2D6) genotype and codeine therapy: 2014 Update","pmid":"24458010","year":2014}]}, 
{"id":100421,"version":4,"name":"HLA-B and Abacavir","url":"https://cpicpgx.org/guidelines/guideline-for-abacavir-and-hla-b/","pharmgkbid":["PA166104997"],**"genes":null,**"publication":[{"title":"Clinical Pharmacogenetics Implementation Consortium Guidelines for HLA-B Genotype and Abacavir Dosing","pmid":"22378157","year":2012}, 
and so on.

**Comment by whaleyr** [comment]
Publication data has been more fleshed out in the table but I'm still working on a permanent solution for filling in more data about each publication as it's imported.
